domains:
  - domain: '{{ app }}.{{ branch }}.{{ environment }}.parallax.dev'
    environments: '*'
    branches: '*'
  - domain: '{{ app }}.{{ environment }}.parallax.dev'
    environments: '*'
    branches: 'master'
  - domain: 'mailhog.parallax.dev'
    environments: 'prod'
    branches: 'master'
afterDeploy:
  delete:
    - kind: Deployment
      namePattern: '{{ app }}-{{ branch }}-*'
      nameApartFrom: '{{ app }}-{{ branch }}-{{ build }}'
      namespace: '{{ namespace }}'