repeat: eachDomain
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: '{{ domain_md5 }}'
  namespace: '{{ namespace }}'
spec:
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - '{{ domain }}'
      - '{{ domain_md5 }}.parallax.dev'
  commonName: '{{ domain_md5 }}.parallax.dev'
  dnsNames:
  - '{{ domain }}'
  - '{{ domain_md5 }}.parallax.dev'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: '{{ domain_md5 }}-ssl'